# Usando a imagem oficial do PostgreSQL
FROM postgres:16

# Definindo variáveis de ambiente para o PostgreSQL
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=postgres

# Expondo a porta padrão do PostgreSQL
EXPOSE 5432
