version: '3.8'
name: Ubuntu-Java-Nginx

services:
  app:
    mem_limit: 512m
    mem_reservation: 128M
    memswap_limit: 1g
    cpus: "0.5"
    cpuset: "1"
    build:
      context: .
      dockerfile: Dockerfile-app
    image: app-image:latest  # Nome da imagem
    container_name: ubuntu_java_nginx
    networks:
      - backend
    ports:
      - "80:80"      # Porta do Nginx
      - "8777:8777"  # Porta da aplicação Java (ajuste conforme necessário)
    depends_on:
      - postgres # Depende do serviço de DB
    restart: always  # Reinicia automaticamente se o serviço cair
  
  postgres:
    mem_limit: 512m
    mem_reservation: 128M
    memswap_limit: 1g
    cpus: "0.5"
    cpuset: "1"
    build:
      context: .
      dockerfile: Dockerfile-postgres
    image: db-image:latest  # Nome da imagem
    container_name: postgres_db
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "54320:5432"  # Porta do PostgreSQL
    restart: on-failure  # Reinicia apenas em caso de falha

networks:
  backend:

volumes:
  postgres_data: