# Usando Ubuntu como imagem base
FROM ubuntu:24.04

# Atualizando o sistema e instalando Java e Nginx
RUN apt-get update && apt-get install -y \
    openjdk-21-jdk \
    nginx \
    && apt-get clean

# Definindo o diretório de trabalho
WORKDIR /app

# Copiando configurações personalizadas do Nginx (opcional)
# Se você tiver um arquivo de configuração customizado, copie-o para o contêiner.
# COPY ./nginx.conf /etc/nginx/nginx.conf

# Expondo portas para o Nginx e a aplicação Java
EXPOSE 80 8080

# Comando para iniciar o Nginx (o contêiner pode ser iniciado com Nginx em execução)
CMD ["sh", "-c", "service nginx start && tail -f /dev/null"]